@extends('layouts.frontend')
@section('title','Home')
@section('styles')
<style>
.theme-nature{background:#f0fdf4;color:#064e3b}.theme-nature .wrap{width:min(1180px,100%);margin:0 auto;padding:0 1.25rem}.nature-hero{padding:4rem 0 2rem}.nature-hero-grid{display:grid;grid-template-columns:minmax(0,.8fr) minmax(300px,1.2fr);gap:1.5rem;align-items:center}.nature-copy{background:#fff;border:1px solid #bbf7d0;border-radius:8px;padding:2rem;box-shadow:0 20px 55px rgba(6,78,59,.12)}.nature-copy h1{font-size:clamp(2.6rem,6vw,5.8rem);line-height:.95;color:#064e3b;margin:0 0 1rem}.nature-copy p{color:#276749;line-height:1.8}.nature-photo{min-height:560px;border-radius:8px;background:linear-gradient(rgba(6,78,59,.08),rgba(6,78,59,.22)),url('https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=80') center/cover}.nature-search{padding:0 0 4rem}.nature-search form{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;background:#dcfce7;border:1px solid #bbf7d0;border-radius:8px;padding:1rem}.nature-search label{font-weight:900;color:#047857;font-size:.8rem}.nature-search input,.nature-search select{width:100%;min-height:44px;border:1px solid #86efac;border-radius:8px;background:#fff;color:#064e3b;padding:0 .75rem}.nature-btn,.nature-search button{background:#059669;color:#fff;border:0;border-radius:8px;padding:.8rem 1rem;font-weight:900;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.nature-trails{padding:4rem 0;background:#dcfce7}.nature-room-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:1rem}.nature-room{background:#fff;border:1px solid #bbf7d0;border-radius:8px;overflow:hidden}.nature-room-img{height:230px;background-size:cover;background-position:center}.nature-room-body{padding:1.2rem}.nature-room h3{color:#064e3b}.nature-price{color:#059669;font-size:1.4rem;font-weight:900}[data-theme="dark"] .theme-nature{background:#052e24;color:#d1fae5}[data-theme="dark"] .nature-copy,[data-theme="dark"] .nature-room,[data-theme="dark"] .nature-search form{background:#063b2f;border-color:rgba(209,250,229,.18)}[data-theme="dark"] .nature-copy h1,[data-theme="dark"] .nature-room h3{color:#d1fae5}[data-theme="dark"] .nature-copy p,[data-theme="dark"] .nature-room p{color:#a7f3d0}@media(max-width:900px){.nature-hero-grid,.nature-search form{grid-template-columns:1fr}.nature-photo{min-height:340px}}
</style>
@endsection
@section('content')
<div class="theme-nature"><section class="nature-hero"><div class="wrap nature-hero-grid"><div class="nature-copy"><span style="color:#059669;font-weight:900;text-transform:uppercase;">{{ $hotelName }}</span><h1>{{ $heroTitle }}</h1><p>{{ $heroSubtitle }}</p><a class="nature-btn" href="{{ route('rooms') }}">Find a stay</a></div><div class="nature-photo"></div></div></section><section class="nature-search"><div class="wrap"><form method="GET" action="{{ route('home') }}"><div><label>Check-in</label><input type="date" name="check_in_date" value="{{ $checkIn }}"></div><div><label>Check-out</label><input type="date" name="check_out_date" value="{{ $checkOut }}"></div><div><label>Guests</label><select name="guests">@for($i=1;$i<=6;$i++)<option value="{{ $i }}" {{ (int)$guestsCount===$i?'selected':'' }}>{{ $i }} Guest{{ $i>1?'s':'' }}</option>@endfor</select></div><div style="display:grid;align-items:end;"><button>Search</button></div></form></div></section><section class="nature-trails"><div class="wrap"><h2 style="font-size:clamp(2rem,4vw,4rem);color:#064e3b;margin:0 0 1rem;">{{ $welcomeTitle }}</h2><p style="max-width:720px;color:#276749;line-height:1.7;">{{ $welcomeDescription }}</p><div class="nature-room-grid">@forelse($roomTypes as $roomType)@php $img=collect($roomType->images??[])->first();$url=$img?(\Illuminate\Support\Str::startsWith($img,['http://','https://','/'])?$img:asset('storage/'.$img)):'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=900&q=80';@endphp<article class="nature-room"><div class="nature-room-img" style="background-image:url('{{ $url }}')"></div><div class="nature-room-body"><h3>{{ $roomType->name }}</h3><p>{{ \Illuminate\Support\Str::limit($roomType->description,95) }}</p><div class="nature-price">{{ $currency }}{{ number_format((float)($roomType->base_price??$roomType->price??0),0) }}</div></div></article>@empty<p>No rooms available at the moment.</p>@endforelse</div></div></section></div>
@endsection
