@extends('layouts.frontend')
@section('title', $title)
@section('meta_title', $page->meta_title ?? $post->meta_title ?? $title)
@section('meta_description', $page->meta_description ?? $post->meta_description ?? $subtitle ?? '')
@section('styles')
<style>
    .theme-public-urban{background:#eef1f5;color:#111827}.theme-public-urban .wrap{width:min(1220px,100%);margin:0 auto;padding:0 1.25rem}.urban-page-hero{background:#111827;color:#fff;padding:4rem 0;border-bottom:6px solid #f59e0b}.urban-page-hero h1{color:#fff;font-size:clamp(2.8rem,6vw,6rem);line-height:.92;margin:.5rem 0}.urban-page-hero p{color:rgba(255,255,255,.72);max-width:720px;line-height:1.75}.urban-page-shell{padding:3rem 0 4.5rem}.urban-command{display:grid;grid-template-columns:280px 1fr;gap:1rem}.urban-command aside{background:#111827;color:#fff;padding:1.25rem;position:sticky;top:6rem}.urban-command aside a{display:block;color:#cbd5e1;padding:.75rem 0;border-bottom:1px solid rgba(255,255,255,.12);font-weight:800}.urban-command aside strong{display:block;color:#f59e0b;font-size:2rem;margin-bottom:1rem}.urban-content{background:#fff;border:1px solid #d9dee7;padding:1.1rem}.theme-public-urban .card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem}.theme-public-urban article,.theme-public-urban details,.theme-public-urban .page-card{background:#f8fafc;border:1px solid #d9dee7;padding:1.2rem}.theme-public-urban .media-block{height:210px;margin:-1.2rem -1.2rem 1rem;overflow:hidden}.theme-public-urban .media-block img{width:100%;height:100%;object-fit:cover}.theme-public-urban .btn-link{background:#f59e0b;color:#111827;padding:.75rem 1rem;font-weight:900;text-decoration:none;display:inline-flex;margin-top:1rem}.theme-public-urban .price{font-weight:900;font-size:1.4rem;color:#111827}[data-theme="dark"] .theme-public-urban{background:#0b1220;color:#e5e7eb}[data-theme="dark"] .urban-content,[data-theme="dark"] .theme-public-urban article,[data-theme="dark"] .theme-public-urban details,[data-theme="dark"] .theme-public-urban .page-card{background:#111827;border-color:rgba(255,255,255,.12);color:#e5e7eb}[data-theme="dark"] .theme-public-urban h3,[data-theme="dark"] .theme-public-urban .price{color:#f9fafb}@media(max-width:900px){.urban-command{grid-template-columns:1fr}.urban-command aside{position:static}}
</style>
@endsection
@section('content')
<div class="theme-public-urban"><section class="urban-page-hero"><div class="wrap"><span style="color:#f59e0b;font-weight:900;text-transform:uppercase;">{{ \App\Helpers\ThemeHelper::getThemeContent('hero_label', $hotelName) }}</span><h1>{{ $title }}</h1>@if($subtitle)<p>{{ $subtitle }}</p>@endif</div></section><section class="urban-page-shell"><div class="wrap urban-command"><aside><strong>{{ \App\Helpers\ThemeHelper::getThemeContent('side_title', 'HQ') }}</strong><a href="{{ route('rooms') }}">Rooms</a><a href="{{ route('services') }}">Services</a><a href="{{ route('contact') }}">Contact</a></aside><div class="urban-content">@include('themes.partials.public-content')</div></div></section></div>
@endsection
